#!/usr/bin/bash

#ip link add <p1-name> type veth peer name <p2-name>
#ip link add <p1-name> netns <p1-ns> type veth peer <p2-name> netns <p2-ns>
#ip link set <p2-name> netns <p2-ns>
#ip link set <p2-name> netns <p2-ns>

ip netns delete dhcpns
ip link del dev dhcp1
ip link del dev dhcp2

ip netns add dhcpns
ip link add dhcp1 type veth peer dhcp2 
ip addr add 10.10.10.1/30 dev dhcp1
ip addr add 10.10.10.2/30 dev dhcp2
ip link set dhcp2 netns dhcpns


sudo ip netns exec dhcpns sudo dhcping
sudo ip netns exec dhcpns ip link

