#!/usr/bin/bash


DHCP_SERVER="/mnt/hgfs/bsherwood/juniper/git/kea/src/bin/dhcp4/kea-dhcp4"

HOOK_LIB="/mnt/hgfs/bsherwood/juniper/git/kea/src/hooks/dhcp/run_script/.libs/libdhcp_run_script.so"



############################################################
function net_stop {

    echo "=== net stop ==="
    ip netns delete dhcpns
    ip link set br2 down
    ip link del dev br2
    #ip link del dev dhcp1
    #ip link del dev dhcp2

}

############################################################
function net_start {

    echo "=== net start ==="
    ip link add br2 type bridge
    ip link add dhcp1 type veth peer dhcp2
    ip link set dhcp1 master br2
    ip addr add 10.10.10.1/24 dev br2
    ip link set br2 up
    ip link set dhcp1 up
    
    ip netns add dhcpns
    ip link set dhcp2 netns dhcpns
    ip link set dhcp1 up
    #ip netns exec dhcpns ip addr add 10.10.10.2/24 dev dhcp2
    ip netns exec dhcpns ip link set dhcp2 up

}

############################################################
function kea_server {

    set -x
    $DHCP_SERVER -d -c etc/kea/kea-dhcp4.conf

}

############################################################
function monitor_queue {

    set -x
    mosquitto_sub -h 10.10.10.1 -t dhcp_server

}

############################################################
function kea_client {

    set -x
    #ip netns exec dhcpns ping -c 2 10.10.10.1
    ip netns exec dhcpns dhclient -d -v 

}

############################################################
function crpd {

    echo "Create crpd01"
    docker run --rm --detach --name crpd01 -h crpd01 --privileged -e SYSLOG_TO_STDOUT='yes' -v "$(pwd)"/crpd01_config:/config -v "$(pwd)"/crpd01_varlog:/var/log -it crpd:22.2R1.9

    #echo "Create interfaces"
    #ip link add dhcp2 type veth peer vdhcp2
    #ip link set dhcp2 master br2

    #echo "Move interface to container"
    #pid=$(docker inspect crpd01 -f '{{.State.Pid}}')
    #ip link set vdhcp2 netns $pid

    #echo "In container, run the following:"
    #echo "ip address add 192.168.10.2/28 dev bgp-net"
    #echo "ip link set bgp-net up"


    echo "Create crpd02"
    docker run --rm --detach --name crpd02 -h crpd02 --privileged -e SYSLOG_TO_STDOUT='yes' -v "$(pwd)"/crpd02_config:/config -v "$(pwd)"/crpd02_varlog:/var/log -it crpd:22.2R1.9


}

############################################################
function check {

    echo "=== check ==="
    set -x
    brctl show br2
    echo ""
    ip addr show dev br2
    echo ""
    ip addr show dev dhcp1
    echo ""
    ip netns exec dhcpns ip addr
    echo ""
    ip netns exec dhcpns ping -c 3 10.10.10.1
}

########## MAIN ##########
############################################################

if [ $# -eq 0 ]; then
    echo "No function provided:"
    echo ""
    compgen -A function
    exit 1
fi


if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

eval "$@"

